# Generated by Django 5.2.8 on 2026-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('negotiating', 'Negotiating'), ('bought', 'Bought'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
    ]
