# Generated by Django 6.0.3 on 2026-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_itemrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='category',
            field=models.CharField(choices=[('charger', 'Charger'), ('battery', 'Battery'), ('screen', 'Screen'), ('keyboard', 'Keyboard'), ('hinge', 'Hinge')], db_index=True, max_length=50),
        ),
    ]
