# Generated by Django 5.2.8 on 2026-03-12 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='activity_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('scam', 'Scammer'), ('inappropriate_content', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('reported_user', 'reported_by', 'activity_type')},
        ),
    ]
